<?php
$stringManager = StringManagerWooUserRolePrices::getInstance();
?>

<span class="festi-user-role-prices-regular-price-lable">
    <?php $stringManager->displayString('cartTotalSavingsRetail'); ?>:
</span> 
<?php echo $regularPrice; ?>
<br />
<span class="festi-user-role-prices-user-price-lable">
    <?php $stringManager->displayString('cartTotalSavingsUserPriceTitle'); ?>:
</span> 
<?php echo $userPrice; ?>
<br />
<span class="festi-user-role-prices-discount-lable">
    <?php $stringManager->displayString('cartTotalSavingsDiscountTitle'); ?>:
</span> 
<?php echo $userDiscount; ?>